### ISSUE TITLE
a new problem with servers data

### ISSUE THREAD

**Issue by ritamarkovich** [denbedilov/ATTENDER#24]
application is searching events in Jerusalem- server returns event in Tel aviv Yafo. a general prblem with city queries.SERVER TO YOUR ATTENTION!

**Comment by ItamarShDev** [comment]
Basically, its Meetups fault. Will fix it soon. 
Thanks

**Comment by ItamarShDev** [comment]
fixed by refreshing the Application team the names of the variables
Closed
