### ISSUE TITLE
Login - server side

### ISSUE THREAD

**Issue by olesyash** [denbedilov/ATTENDER#6]
Server side: 
- [x] Google+ login support from the server side

**Comment by robi-y** [comment]
Why not use FB login?

**Comment by olesyash** [comment]
We have the both options. Facebook login, or email registration. They are
in different issues
Thank you for your attention!

2015-04-26 9:46 GMT+03:00 robi-y <notifications@github.com>:

**Comment by olesyash** [comment]
Done but need to be checked by APP side and to send name and lastname
